project:
  type: website
  preview:
    port: 4200
    browser: true
  
  
website:
  title: "biosteve.github.io"
  navbar:
    logo: "C:/Users/stefa/Desktop/R Projects/biosteve.github.io/images/Logo.png"
    pinned: True
    right:
      - href: index.qmd
        text: Home
      - resume.qmd
      - about.qmd
      - monographs.qmd
      - technical_publications.qmd

format:
  html:
    theme:
      - solar
    css: styles.css
    toc: true

editor: visual

