---
title: "Technical Publications"
---


Original Articles

::: {style="text-align: justify;"}
* Antinero, A., Printzi, A., Kourkouta, C., **Fragkoulis, S.**, Mazurais, D., Zambonino-Infante, J.L., & Koumoundouros, G. (2023). The role of starter diets in the development of skeletal abnormalities in zebrafish _Danio rerio_ (Hamilton, 1822). _Journal of Fish Diseases_, 46, 697–705 | DOI: <https://doi.org/10.1111/jfd.13779>

    **Abstract**
  
  _Fish skeletal development has long been correlated with nutritional factors. Lack of zebrafish nutritional standardization, especially during the early stages, decreases the reproducibility of the conducted research. The present study represents an evaluation of four commercial (A, D, zebrafish specific; B, generic for freshwater larvae; C, specific for marine fish larvae) and one experimental (Ctrl) early diets on zebrafish skeletal development. Skeletal abnormalities rates in the different experimental groups were assessed at the end of the larval period (20 days post-fertilization, dpf) and after a swimming challenge test (SCT, 20–24 dpf). At 20 dpf, results revealed a significant effect of diet on the rate of caudal-peduncle scoliosis and gill-cover abnormalities, which were relatively elevated in B and C groups. SCT results focused on swimming-induced lordosis, which was comparatively elevated in diets C and D (83% ± 7% and 75% ± 10%, respectively, vs. 52% ± 18% in diet A). No significant effects of dry diets were observed on the survival and growth rate of zebrafish. Results are discussed with respect to the deferential diet composition between the groups and the species requirements. A  potential nutritional control of haemal lordosis in finfish aquaculture is suggested._
  
* **Fragkoulis, S.**, Kourkouta, C., Geladakis, G., Printzi, A., Glaropoulos, A. & Koumoundouros, G. (2022). Recovery of Haemal Lordosis in European Seabass _Dicentrarchus labrax_ (Linnaeus 1758). _Aquaculture Journal_, 2, 1-12 | DOI: <https://doi.org/10.3390/aquacj2010001>

  **Abstract**
  
  _Lordosis of the haemal part of the vertebral column is a frequent abnormality in reared fish. Haemal lordosis develops during the late larval and early juvenile life stages of fish, mainly due to the high swimming activity of the fish in the rearing tanks. In the present study, we have examined whether haemal lordosis recovers during the growth of European seabass. Furthermore, we aimed to develop simple morphometric indices (PrAn1 and PrAn2) that might link the severity of lordosis at the juvenile stage with fish morphological quality at harvesting. At 111 days post-hatching (dph, 53 ± 4 mm standard length, SL), 600 seabass juveniles with lordotic (L, 200 fish) or normal (N, 400 fish) external morphology were selected and introduced in a common tank. At 150 dph (75 ± 7 mm SL), 350 fish were randomly selected, pit-tagged and transferred to a sea cage for on-growing up to 502 dph (234 ± 16 mm SL). The morphological examination of the fish at 150 and 502 dph revealed that 60% (46 out of 77) of L juveniles turned into normal phenotype by the end of on-growing period. Interestingly, 56% of the fish with recovered external morphology (N-Rec) presented either a completely normal vertebral column (31%) or minor abnormalities of individual vertebrae (25%). Following the results of geometric morphometric analysis, the differences in the body shape between N-Rec and N fish were not statistically significant (p > 0.05, canonical variate analysis). The examined morphometric indices were effective in discriminating the normal fish from 58% (PrAn1) to 65% (PrAn2) of lordotic juveniles. Results are discussed with respect to the mechanism of lordosis recovery, and spotlights on their application for quality control and cull out of the abnormal fish in commercial hatcheries._


* **Fragkoulis, S.**, Kerasovitis, D., Batargias, C. & Koumoundouros G. (2021). Body-shape trajectories and their genetic variance component in Gilthead seabream (_Sparus aurata_ L.). _Scientific Reports_ 11, 16964 | DOI: <https://doi.org/10.1038/s41598-021-95726-9>

   **Abstract**
   
   _The phenotype of juvenile fish is closely associated with the adult phenotype, thus consisting an important quality trait for reared fish stocks. In this study, we estimated the correlation between the juvenile and adult body-shape in Gilthead seabream, and examined the genetic basis of the ontogenetic trajectories. The body shape of 959 pit-tagged fish was periodically examined during the juvenile-to-adult period. Individual shape ontogenetic trajectories were studied in respect to the initial (juvenile) and final (adult) phenotypes, as well as to the rate that adult phenotype is attained (phenotypic integration rate). We found that the juvenile body-shape presented a rapid change up to 192.7 ± 1.9 mm standard length, followed by a phenotypically stable period (plateau). Depending on the shape component considered, body-shape correlations between juvenile and adult stages ranged from 0.22 to 0.76. Heritability estimates (h2) of the final phenotype ranged from 0.370 ± 0.077 to 0.511 ± 0.089, whereas h2 for the phenotypic integration rate was 0.173 ± 0.062. To our knowledge, this is the first study demonstrating that the variance of the ontogenetic trajectories has a substantial additive genetic component. Results are discussed in respect to their potential use in selective breeding programs of Gilthead seabream._


* Printzi, A., Kourkouta, C., **Fragkoulis, S.**, Dimitriadi, A., Geladakis, G., Orfanakis, M., Mazurais, D., Zambonino-Infante, J.L., & Koumoundouros, G. (2021). Balancing between Artemia and microdiet usage for normal skeletal development in zebrafish (_Danio rerio_). _Journal of Fish Diseases_, 44, 1689–1696 | DOI: <https://doi.org/10.1111/jfd.13487>

  **Abstract**
  
  _Targeting in zebrafish fast growth, high survival rates and improved reproductive performance has led over the last years in variable feeding regimes between different facilities. Despite its significance on fish function and welfare, normal skeletal development has rarely been evaluated in establishing the best feeding practices for zebrafish. The aim of this study was to establish a protocol for normal skeletal development, growth and survival of zebrafish larvae through live feed-to-microdiet transition at an appropriate rate. Four feeding regimes including feeding exclusively on Artemia nauplii (A) or dry microdiet (D), and feeding on both Artemia and microdiet at two different transition rates (slow (B) or fast (C)) were applied from 5 to 24 dpf (days post-fertilization). Results demonstrated a significant effect of feeding regimes on the incidence of skeletal abnormalities (gill cover, fins and vertebral column, p < .05) in zebrafish larvae. The A and B experimental groups presented the highest (88 ± 3 and 84 ± 17%, respectively), but the C and D the lowest (18 ± 14 and 11 ± 2%, respectively), rates of normal fish (fish without any abnormality). Similarly, growth rate was comparatively elevated in A and B groups. No significant differences were observed in fish survival between A, B and C groups. However, D group presented a significantly lower survival rate. To our knowledge, this is the first study to show that the live feed-to-microdiet transition rate influences larval growth, survival and abnormality rates in a non-homogenous pattern._

* **Fragkoulis, S.** & Koumoundouros G. (2021). Simple morphometrics for predicting lordosis-induced deviations of body shape in reared Gilthead seabream (_Sparus aurata_ L.). _Journal of Fish Diseases_, 44, 1265-1267 | DOI: <https://doi.org/10.1111/jfd.13384>

* **Fragkoulis, S.**, Economou, I., Moukas, G., Koumoundouros, G. & Batargias, C. (2020). Caudal fin abnormalities in Gilthead seabream (_Sparus aurata_ L.) have a strong genetic variance component. _Journal of Fish Diseases_, 43, 825-828 | DOI: <https://doi.org/10.1111/jfd.13180>

* Printzi, A., **Fragkoulis, S.**, Dimitriadi, A., Keklikoglou, K., Arvanitidis, C., Witten, P.E. & Koumoundouros, G. (2019). Exercise-induced lordosis in zebrafish _Danio rerio_ (Hamilton, 1822). _Journal of Fish Diseases_, 98, 987-994 | DOI: <https://doi.org/10.1111/jfb.14240>

   **Abstract**
   
   _The anabolic effect of exercise on muscles and bones is well documented. In teleost fish, exercise has been shown to accelerate skeletogenesis, to increase bone volume, and to change the shape of vertebral bodies. Still, increased swimming has also been reported to induce malformations of the teleost vertebral column, particularly lordosis. This study examines whether zebrafish (Danio rerio) develops lordosis as a result of continuous physical exercise. Zebrafish were subjected, for 1 week, to an increased swimming exercise of 5.0, 6.5 or 8.0 total body lengths (TL) per second. Control and exercise group zebrafish were examined for the presence of vertebral abnormalities, by in vivo examination, whole mount staining for bone and cartilage and histology and micro-computed tomography (CT) scanning. Exercise zebrafish developed a significantly higher rate of lordosis in the haemal part of the vertebral column. At the end of the experiment, the frequency of lordosis in the control groups was 0.5 ± 1.3% and that in the exercise groups was 7.5 ± 10.6%, 47.5 ± 10.6% and 92.5 ± 6.0% of 5.0, 6.5 and 8.0 TL∙s−1, respectively. Histological analysis and CT scanning revealed abnormal vertebrae with dorsal folding of the vertebral body end plates. Possible mechanisms that trigger lordotic spine malformations are discussed. This is the first study to report a quick, reliable and welfare-compatible method of inducing skeletal abnormalities in a vertebrate model during the post-embryonic period._


* **Fragkoulis, S.**, Printzi, A., Geladakis, G., Katribouzas, N. & Koumoundouros, G. (2019). Recovery of haemal lordosis in Gilthead seabream (_Sparus aurata_ L.). _Scientific Reports_ 9, 9832 | DOI: <https://doi.org/10.1038/s41598-019-46334-1>

  **Abstract**
  
  _Haemal lordosis is a frequent abnormality of the vertebral column. It has been recorded to develop in different finfish species, during the hatchery rearing phase. Under certain conditions, this abnormality reaches a high prevalence and severity degree, with significant effects on the external morphology of the fish. We show that haemal lordosis recovers during the on-growing of Gilthead seabream in sea cages. At the end of the hatchery phase, 1700 seabream juveniles were tagged electronically and examined for the presence of haemal lordosis. Subsequently, their morphology was examined periodically up to the end of the on-growing period. We found that the prevalence of fish with a lordotic external morphology decreased during the studied period by approximately 50%. Interestingly, 27% of the recovered fish presented a completely normal vertebral column. Geometric morphometric analysis showed no significant differences in the body shape between the fish with a recovered normal phenotype and the fish that were normal since the beginning of the on-growing period. Our results provide the first evidence for the recovery of lordosis during the growth of fish. A mechanism with multiple levels of remodeling of abnormal bones is suggested._
  
* **Fragkoulis, S.**,  Batargias, C., Kolios, P. & Koumoundouros, G. (2018).Genetic parameters of the upper-jaw abnormalities in Gilthead seabream _Sparus aurata_. Aquaculture, 497, 226-233 | DOI: <https://doi.org/10.1016/j.aquaculture.2018.07.071>

  **Abstract**
  _The development of skeletal abnormalities is a frequent problem of quality in finfish hatcheries, resulting from unfavourable environmental conditions, often under the control of genetic background. In the present study, the heritability of jaw abnormalities in Gilthead seabream was estimated at the end of the larval rearing phase (39 dph, days post hatching). All larvae came from eggs obtained by mass spontaneous spawn of a common brood stock of a commercial hatchery. Skeletal abnormalities were examined after the double staining of the larvae for bone and cartilage. Macroscopically, three abnormality types were recorded in the studied larvae, pugheadness (Pug, 6.7%), lateral displacement of the upper jaw (LdUj, 2.3%) and crossbite (Crbt, 0.9%). The microscopic examination of the specimens revealed the frequent presence of internal abnormalities (e.g. fusions, size reductions, bending) which had not any clear effect on the external morphology of the fish (silent abnormalities). Each stained larva was genotyped and parentally assigned. Heritability estimates were insignificant for the three types of gross, externally-visible, abnormalities of the jaws (Pug, LdUj, Crbt). On the contrary, significant heritabilities were estimated for the internal abnormalities which are associated to LdUj (e.g. fusion of maxillaries with pre-maxillaries, 0.22 ± 0.06). Interestingly, the consideration of all the abnormalities of the upper jaw as a uniform trait resulted to the estimation of insignificant heritabilities, and therefore to the masking of the significant genetic component of the LdUj abnormality. Results are discussed in respect to their potential value for the selective breeding programs of Gilthead seabream._

* Crespel, A., Zambonino-Infante, J.L., Mazurais, D. Koumoundouros, G., **Fragkoulis, S.**, Quazuguel, P., Huelvan, C., Madec, L., Servili, A. & Claireaux, G. (2018). The development of contemporary European sea bass larvae (_Dicentrarchus labrax_) is not affected by projected ocean acidification scenarios. _Marine Biology_, 164, 155 | DOI: <https://doi.org/10.1007/s00227-017-3178-x>

  **Abstract**
  
  _Ocean acidification is a recognized consequence of anthropogenic carbon dioxide (CO2) emission in the atmosphere. Despite its threat to marine ecosystems, little is presently known about the capacity for fish to respond efficiently to this acidification. In adult fish, acid–base regulatory capacities are believed to be relatively competent to respond to hypercapnic conditions. However, fish in early life stage could be particularly sensitive to environmental factors as organs and important physiological functions become progressively operational during this period. In this study, the response of European sea bass (Dicentrarchus labrax) larvae reared under three ocean acidification scenarios, i.e., control (present condition,  $P_{\text{CO}_2}$ = 590 µatm, pH total=7.9), low acidification (intermediate IPCC scenario, $P_{\text{CO}_2}$ = 980 µatm, pH total=7.7), and high acidification (most severe IPCC scenario, $P_{\text{CO}_2}$ = 1520 µatm, pH total=7.5) were compared across multiple levels of biological organizations. From 2 to 45 days-post-hatching, the chronic exposure to the different scenarios had limited influence on the survival and growth of the larvae (in the low acidification condition only) and had no apparent effect on the digestive developmental processes. The high acidification condition induced both faster mineralization and reduction in skeletal deformities. Global (microarray) and targeted (qPCR) analysis of transcript levels in whole larvae did not reveal any significant changes in gene expression across tested acidification conditions. Overall, this study suggests that contemporary sea bass larvae are already capable of coping with projected acidification conditions without having to mobilize specific defense mechanisms._

* **Fragkoulis, S.**, Christou M., Karo, R., Ritas, C., Tzokas, C., Batargias, C. & Koumoundouros, G. (2016). Scaling of body-shape quality in reared gilthead seabream _Sparus aurata_ L. Consumer preference assessment, wild standard and variability in reared phenotype. _Aquaculture Research_, 48, 2402-2410 | DOI: <https://doi.org/10.1111/are.13076>

  **Abstract**
  _In this study, a scale of quality for the body shape of Gilthead seabream was developed. For this purpose, a questionnaire survey was carried out to study the preferences of consumers for the body shape of seabream. Furthermore, the variation in body shape in reared seabream was studied under two rearing environments (sea cages vs. tanks) and in comparison with wild-caught individuals. Following the test–retest analysis of reliability, the 22 of 65 participants in the survey presented a significant correlation between repeated evaluations of the same subjects and were classified as responders of high discrimination efficiency or/and reliability (HDR). Geometric morphometric analysis on the evaluation of HDR responders revealed that compared with the fish of fair body shape, fish with preferred body shape were characterized mainly by a more proximal position of the base of the pelvic fins, the anterior base of the anal fin and the anterior dorsal fin. Of the 45 wild-caught specimens examined, 26 presented a normal lateral line and no obvious skeletal deformities. The body shape of the normal wild-caught fish was compared with the shape of reared seabream. Results showed that both the origin of fish (wild vs. reared) and the rearing methodology during the on-growing phase significantly affected the body shape of seabream (P < 0.001). Compared with the reared fish, the wild-caught fish were characterized mainly by a less prominent belly, slender trunk, smaller head, shorter caudal peduncle and a more posterior-ventral position of the upper jaw._
  
* **Fragkoulis, S.**, Paliogiannis, H., Kokkinias, P., Chiers, K., Adriaens, D. & Koumoundouros, G. (2016). Saddleback syndrome in European sea bass _Dicentrarchus labrax_ (Linnaeus, 1758): anatomy, ontogeny and correlation with lateral-line, anal and pelvic fin abnormalities. _Journal of Fish Diseases_, 40, 83-95 | DOI: <https://doi.org/10.1111/jfd.12494>

  **Abstract**
  _This study focused on the anatomy and ontogeny of saddleback syndrome (SBS) in reared European sea bass. The abnormality was detected at an unusually high frequency (12–94%) during a routine quality control in a commercial hatchery. Anatomically the abnormality was mainly characterized by the loss of 1–5 hard spines and severe abnormalities of the proximal pterygiophores (anterior dorsal fin), size reduction of a few lepidotrichia, missing lepidotrichia and/or lepidotrichia of poor ossification (posterior dorsal fin). SBS was significantly correlated with abnormalities of the anal and pelvic fins in all the examined populations. Moreover, in juvenile fish, SBS was significantly correlated with an abnormal lack of sectors of the lateral line. The examination of early larval samples revealed that SBS was ontogenetically associated with severe abnormalities of the primordial marginal finfold, which developed at the flexion stage (ca 8.5–11.0 mm SL). Histologically, these abnormalities were associated with extensive epidermal erosion. The results are discussed in respect of the critical ontogenetic period and the possible causative factors of SBS in European sea bass. It is suggested that causative factors acted during a wide ontogenetic period including flexion and metamorphosis phases._

:::



Conference Proceedings --> Upload my pdfs as hyperlinked!!



Theses/Monographs (in reverse chronological order)

* (June 2025 - March 2026) M.Sc Title: _Analysis of the evolutionary history of eukaryotic genes in relation to their spatial arrangement in the eukaryotic nucleus_

  Location: Biomedical Sciences Research Center "Alexander Fleming", Athens, Greece

* (June 2016 - December 2020) Ph.D Title: _xxxxxxxxx_

  Location: Biology Department, University of Crete, Heraklion, Greece

* (September 2013 - November 2014) M.Sc Title: _xxxxx_

  Location: Biology Department, University of Crete, Heraklion, Greece
